name: Download

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        #default: 'true'
        #required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: download
        run: |
          git config --local user.email "justjavac@gmail.com"
          git config --local user.name "è¿·æ¸¡"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git lfs install

          ./bin/youtube-dl  -f best --config-location config.txt
          git lfs track "downloads/*.*"
          git add .gitattributes
          git add .
          git commit -m "download youtube video"
          ##git push

      - name: Start SSH via tmate
        uses: VPN-V2Ray/ssh2githubactions@main
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      
      - name: Organize files 
        run: |
             tar -czf Downloads.tar.gz downloads/

      - name: Upload firmware to WeTransfer 
        #if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
        if: always()
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer wet -s -p 16 --no-progress Downloads.tar.gz 2>&1 | tee wetransfer.log
          echo "::warning ðŸŒ file=wetransfer.com::$(cat wetransfer.log | grep https)"
        

      - name: Organize files 
        run: |
             git rm -fr --cached downloads/*.mp4
             echo "">playlist.txt
             #git rm -f playlist.txt
             #git add playlist.txt
             echo test > playlist.txt
             git commit -m 'del' 
             git push -u origin
             
      #- name: Start SSH via tmate
      #  uses: VPN-V2Ray/ssh2githubactions@main
      #  env:
      #    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

